version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/exp_management
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - mongodb
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "3333:3333"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
